apiVersion: v1 # for versions before 1.6.0 use extensions/v1beta1
kind: Pod
metadata:
  name: ftp-server
  labels:
    app: ftp-server
spec:
  containers:
  - name: load-tests-ftp-container
    image: fauria/vsftpd
    ports:
    - containerPort: 21
      protocol: TCP
      name: "ftp-server"
    env:
    - name: FTP_USER
      value: "user"
    - name: FTP_PASS
      value: "pass1234"
    volumeMounts:
      - mountPath: /home/vsftpd/user
        name: pv-storage
  volumes:
    - name: pv-storage
      persistentVolumeClaim:
        claimName: load-test-pvc